default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: debt_manager_development
  username: <%= ENV["DEBT_MANAGER_DATABASE_USERNAME"] %>
  password: "<%= ENV["DEBT_MANAGER_DATABASE_PASSWORD"] %>"

test:
  <<: *default
  database: debt_manager_test
  username: <%= ENV["DEBT_MANAGER_DATABASE_USERNAME"] %>
  password: "<%= ENV["DEBT_MANAGER_DATABASE_PASSWORD"] %>"

production:
  <<: *default
  database: debt_manager_production
  password: "<%= ENV["DEBT_MANAGER_DATABASE_PASSWORD"] %>"
