default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: debt_manager_development
  username: postgres
  password: '@Ajibaye1'

test:
  <<: *default
  database: debt_manager_test
  username: postgres
  password: '@Ajibaye1'

production:
  <<: *default
  database: debt_manager_production
  password: <%= ENV["DEBT_MANAGER_DATABASE_PASSWORD"] %>
